### ISSUE TITLE
Element query executed before Craft is fully initialized

### ISSUE THREAD

**Issue by boudewijn-zicht** [jamesedmonston/graphql-authentication#140]
Hello!

The logs are filled with `Element query executed before Craft is fully initialized` messages.  This is trigged when the plugin is initialized, and that occurs at times when the database is not yet available.

Is it possible to run the `craft\web\User->getIsAdmin()` on demand instead of at plugin init?

See the below stacktrace for the call to: `/index.php?dontExtendSession=1&p=admin%2Factions%2Fusers%2Fsession-info&site=default`

```
2023-12-11 15:10:50 [web.WARNING] [craft\elements\db\ElementQuery::prepare] Element query executed before Craft is fully initialized. Stack trace:
#0 /home/userapp/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare()
#1 /home/userapp/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build() 
#2 /home/userapp/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand() 
#3 /home/userapp/vendor/craftcms/cms/src/db/Query.php(275): yii\db\Query->one() 
#4 /home/userapp/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1604): craft\db\Query->one() 
#5 /home/userapp/vendor/craftcms/cms/src/elements/User.php(545): craft\elements\db\ElementQuery->one() 
#6 /home/userapp/vendor/yiisoft/yii2/web/User.php(698): craft\elements\User::findIdentity() 
#7 /home/userapp/vendor/craftcms/cms/src/web/User.php(489): yii\web\User->renewAuthStatus() 
#8 /home/userapp/vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus() 
#9 /home/userapp/vendor/craftcms/cms/src/web/User.php(257): yii\web\User->getIdentity() 
#10 /home/userapp/vendor/jamesedmonston/graphql-authentication/src/GraphqlAuthentication.php(207): craft\web\User->getIsAdmin() 
#11 /home/userapp/vendor/yiisoft/yii2/base/BaseObject.php(109): jamesedmonston\graphqlauthentication\GraphqlAuthentication->init() 
#12 /home/userapp/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject->__construct() 
#13 /home/userapp/vendor/craftcms/cms/src/base/Plugin.php(122): yii\base\Module->__construct() 
#14 craft\base\Plugin->__construct() 
#15 /home/userapp/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs() 
#16 /home/userapp/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build() 
#17 /home/userapp/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get() 
#18 /home/userapp/vendor/craftcms/cms/src/Craft.php(59): yii\BaseYii::createObject() 
#19 /home/userapp/vendor/craftcms/cms/src/services/Plugins.php(943): Craft::createObject() 
#20 /home/userapp/vendor/craftcms/cms/src/services/Plugins.php(228): craft\services\Plugins->createPlugin() 
#21 /home/userapp/vendor/craftcms/cms/src/base/ApplicationTrait.php(1616): craft\services\Plugins->loadPlugins() 
#22 /home/userapp/vendor/craftcms/cms/src/web/Application.php(109): craft\web\Application->_postInit() 
#23 /home/userapp/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init() 
#24 /home/userapp/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct() 
#25 yii\base\Application->__construct() 
#26 /home/userapp/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs() 
#27 /home/userapp/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build() 
#28 /home/userapp/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get() 
#29 /home/userapp/vendor/craftcms/cms/src/Craft.php(59): yii\BaseYii::createObject() 
#30 /home/userapp/vendor/craftcms/cms/bootstrap/bootstrap.php(250): Craft::createObject() 
#31 /home/userapp/vendor/craftcms/cms/bootstrap/web.php(40): require() 
#32 /home/userapp/web/index.php(24): require()
```

Hopefully this is easy to fix, it would make our logs much more readable.

**Comment by ryssbowh** [comment]
I'm also getting this issue on 2.5.0

**Comment by torgeirbeyer** [comment]
I'm seeing this issue as well on 2.5.0

**Comment by smnedelko** [comment]
The bug has not been fixed.

**Comment by Romanavr** [comment]
I have the same issue.
`
#10 /site/vendor/jamesedmonston/graphql-authentication/src/GraphqlAuthentication.php(207): craft\web\User->getIsAdmin()
`
If it's helps, see the debug line where it happens.
Plugin version `2.5.0.`
