### ISSUE TITLE
Type Error when accessing settings

### ISSUE THREAD

**Issue by daltonrooney** [jamesedmonston/graphql-authentication#26]
Me again. I'm just going to keep breaking your plugin all weekend. 😀

Trying to access the settings page and I'm getting this:

```
TypeError: Argument 1 passed to jamesedmonston\graphqlauthentication\controllers\SettingsController::_getSchemaPermissions() must be an instance of craft\models\GqlSchema, null given, called in /home/hcps/webapps/hcps-api-dev/releases/19869138bf56138d7e6b78bb944872f5b520d23f/craft/vendor/jamesedmonston/graphql-authentication/src/controllers/SettingsController.php on line 120 and defined in /home/hcps/webapps/hcps-api-dev/releases/19869138bf56138d7e6b78bb944872f5b520d23f/craft/vendor/jamesedmonston/graphql-authentication/src/controllers/SettingsController.php:148
Stack trace:
#0 /home/hcps/webapps/hcps-api-dev/releases/19869138bf56138d7e6b78bb944872f5b520d23f/craft/vendor/jamesedmonston/graphql-authentication/src/controllers/SettingsController.php(120): jamesedmonston\graphqlauthentication\controllers\SettingsController->_getSchemaPermissions()
#1 [internal function]: jamesedmonston\graphqlauthentication\controllers\SettingsController->actionIndex()
#2 /home/hcps/webapps/hcps-api-dev/releases/19869138bf56138d7e6b78bb944872f5b520d23f/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 /home/hcps/webapps/hcps-api-dev/releases/19869138bf56138d7e6b78bb944872f5b520d23f/craft/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#4 /home/hcps/webapps/hcps-api-dev/releases/19869138bf56138d7e6b78bb944872f5b520d23f/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#5 /home/hcps/webapps/hcps-api-dev/releases/19869138bf56138d7e6b78bb944872f5b520d23f/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#6 /home/hcps/webapps/hcps-api-dev/releases/19869138bf56138d7e6b78bb944872f5b520d23f/craft/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#7 /home/hcps/webapps/hcps-api-dev/releases/19869138bf56138d7e6b78bb944872f5b520d23f/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#8 /home/hcps/webapps/hcps-api-dev/releases/19869138bf56138d7e6b78bb944872f5b520d23f/craft/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest()
#9 /home/hcps/webapps/hcps-api-dev/releases/19869138bf56138d7e6b78bb944872f5b520d23f/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#10 /home/hcps/webapps/hcps-api-dev/releases/19869138bf56138d7e6b78bb944872f5b520d23f/public/index.php(21): yii\base\Application->run()
#11 {main}
```

Any thoughts? I did just delete a schema, which _may_ have been applied to a group. I probably should have removed it from the group first, yeah?

**Comment by jamesedmonston** [comment]
@daltonrooney Just deleted a schema that was assigned to a user group and I'm getting the same error, too. Will fix!
