### ISSUE TITLE
Header Authorization problem - after upgrade

### ISSUE THREAD

**Issue by GMConsultant** [jamesedmonston/graphql-authentication#53]
Hi James, 
After a test on production enviroment, if I remove the htaccess directive, the login run OK BUT all others GraphQL has problem: 

```
{
    "errors": [
        {
            "message": "Tried to load an unregistered type \"xxxxx_GlobalSet\". This can indicate both a typo in the query or an issue with the schema used."
        }
    ]
}

```
If I enable the htaccess directive ( after login ) all are ok.

There is a Authorization header problem into the plugin....

_Originally posted by @GMConsultant in https://github.com/jamesedmonston/graphql-authentication/issues/52#issuecomment-831154582_

**Comment by GMConsultant** [comment]
I downgraded to 1.7.0  and all are ok.

**Comment by magicspon** [comment]
I'm also seeing this issue with 1.8.0

**Comment by GMConsultant** [comment]
FYI this is the error:

```
{
    "name": "Exception",
    "message": "Invalid Authorization Header",
    "code": 0,
    "type": "GraphQL\\Error\\Error",
    "file": "/home/*******/craft/vendor/jamesedmonston/graphql-authentication/src/services/ErrorService.php",
    "line": 14,
    "stack-trace": [
        "#0 /home/bibici/craft/vendor/jamesedmonston/graphql-authentication/src/services/TokenService.php(234): jamesedmonston\\graphqlauthentication\\services\\ErrorService->throw()",
        "#1 /home/bibici/craft/vendor/jamesedmonston/graphql-authentication/src/services/RestrictionService.php(277): jamesedmonston\\graphqlauthentication\\services\\TokenService->getHeaderToken()",
        "#2 /home/bibici/craft/vendor/jamesedmonston/graphql-authentication/src/services/TokenService.php(243): jamesedmonston\\graphqlauthentication\\services\\RestrictionService->shouldRestrictRequests()",
        "#3 [internal function]: jamesedmonston\\graphqlauthentication\\services\\TokenService->rewriteJwtHeader()",
        "#4 /home/bibici/craft/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()",
        "#5 /home/bibici/craft/vendor/yiisoft/yii2/base/Component.php(637): yii\\base\\Event::trigger()",
        "#6 /home/bibici/craft/vendor/yiisoft/yii2/base/Controller.php(300): yii\\base\\Component->trigger()",
        "#7 /home/bibici/craft/vendor/yiisoft/yii2/web/Controller.php(214): yii\\base\\Controller->beforeAction()",
        "#8 /home/bibici/craft/vendor/craftcms/cms/src/web/Controller.php(138): yii\\web\\Controller->beforeAction()",
        "#9 /home/bibici/craft/vendor/craftcms/cms/src/controllers/GraphqlController.php(63): craft\\web\\Controller->beforeAction()",
        "#10 /home/bibici/craft/vendor/yiisoft/yii2/base/Controller.php(179): craft\\controllers\\GraphqlController->beforeAction()",
        "#11 /home/bibici/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\\base\\Controller->runAction()",
        "#12 /home/bibici/craft/vendor/yiisoft/yii2/base/Module.php(534): craft\\web\\Controller->runAction()",
        "#13 /home/bibici/craft/vendor/craftcms/cms/src/web/Application.php(274): yii\\base\\Module->runAction()",
        "#14 /home/bibici/craft/vendor/yiisoft/yii2/web/Application.php(104): craft\\web\\Application->runAction()",
        "#15 /home/bibici/craft/vendor/craftcms/cms/src/web/Application.php(259): yii\\web\\Application->handleRequest()",
        "#16 /home/bibici/craft/vendor/yiisoft/yii2/base/Application.php(392): craft\\web\\Application->handleRequest()",
        "#17 /home/bibici/craft/web/home.php(26): yii\\base\\Application->run()",
        "#18 {main}"
    ]
}
```

**Comment by jamesedmonston** [comment]
Looks like https://github.com/jamesedmonston/graphql-authentication/pull/48 must’ve broken something. I’m out at the moment – will take a look this evening.

Cheers

**Comment by jamesedmonston** [comment]
@GMConsultant @magicspon would you be able to try https://github.com/jamesedmonston/graphql-authentication/commit/83674b20af571fb683e558d9f0bc084ee74696a7 and let me know if that fixes the issue for you, please?

**Comment by GMConsultant** [comment]
Hi James,
I've installed with: 
`composer require jamesedmonston/graphql-authentication:dev-develop`
But it's the same....

[GraphQL_Error_Error.pdf](https://github.com/jamesedmonston/graphql-authentication/files/6420484/GraphQL_Error_Error.pdf)

**Comment by jamesedmonston** [comment]
@GMConsultant Thanks for the attached PDF – that's pointed me in the right direction. Fixing now!

**Comment by jamesedmonston** [comment]
@GMConsultant would be great if you could try updating again to see if the latest commit has resolved it. Sorry for the hassle!

**Comment by GMConsultant** [comment]
YES!!!!! NOW it' s OK!

**Comment by jamesedmonston** [comment]
@GMConsultant Awesome! Will get this rolled into a release later on today 👍

**Comment by jamesedmonston** [comment]
@GMConsultant @magicspon I've just pushed out `1.9.0` that has this fix in. Thanks!
