### ISSUE TITLE
Variable "namespace" does not exist.

### ISSUE THREAD

**Issue by Tam** [jamesedmonston/graphql-authentication#93]
When trying to view the settings page:

```diff,twig
{% extends '_layouts/cp' %}
{% set title = 'GraphQL Authentication' %}
 
{% block content %}
    <input type="hidden" name="action" value="plugins/save-plugin-settings">
    <input type="hidden" name="pluginHandle" value="graphql-authentication">
 
-    {% namespace namespace %}
    <div id="users">
      {% include 'graphql-authentication/_sections/users' %}
    </div>
 
    <div id="tokens" class="hidden">
      {% include 'graphql-authentication/_sections/tokens' %}
    </div>
 
    <div id="fields" class="hidden">
```

Craft: Craft Pro 3.7.40
Auth Plugin: 1.12.3

```
Twig\Error\RuntimeError: Variable "namespace" does not exist. in /var/www/html/vendor/jamesedmonston/graphql-authentication/src/templates/settings.twig:8
Stack trace:
#0 /var/www/html/storage/runtime/compiled_templates/3a/3a70a9f78bc41bfcae672ff11b5613c0.php(61): __TwigTemplate_e4ce698b081f7ea2ac0a0b71eee8c1dc->{closure}()
#1 /var/www/html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_e4ce698b081f7ea2ac0a0b71eee8c1dc->block_content(Array, Array)
#2 /var/www/html/storage/runtime/compiled_templates/c9/c9435e8f8e82c1ccaa8e5f4bec2aba6e.php(535): Twig\Template->displayBlock('content', Array, Array)
#3 /var/www/html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_975334dc99a4585460ebbfc55e6e6bb6->block_main(Array, Array)
#4 /var/www/html/storage/runtime/compiled_templates/c9/c9435e8f8e82c1ccaa8e5f4bec2aba6e.php(346): Twig\Template->displayBlock('main', Array, Array)
#5 /var/www/html/vendor/twig/twig/src/Template.php(182): __TwigTemplate_975334dc99a4585460ebbfc55e6e6bb6->block_body(Array, Array)
#6 /var/www/html/storage/runtime/compiled_templates/cf/cf145cd053aae2b0466f80c1e99e79a5.php(96): Twig\Template->displayBlock('body', Array, Array)
#7 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_94de00319f433a8166292a3e04bf2dfa->doDisplay(Array, Array)
#8 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#9 /var/www/html/storage/runtime/compiled_templates/d2/d21f9f976609df11ac11f5cc7dd53f04.php(56): Twig\Template->display(Array, Array)
#10 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_d3004dc42ad27099b4e9c811a007cb08->doDisplay(Array, Array)
#11 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /var/www/html/storage/runtime/compiled_templates/c9/c9435e8f8e82c1ccaa8e5f4bec2aba6e.php(165): Twig\Template->display(Array, Array)
#13 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_975334dc99a4585460ebbfc55e6e6bb6->doDisplay(Array, Array)
#14 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /var/www/html/storage/runtime/compiled_templates/3a/3a70a9f78bc41bfcae672ff11b5613c0.php(46): Twig\Template->display(Array, Array)
#16 /var/www/html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_e4ce698b081f7ea2ac0a0b71eee8c1dc->doDisplay(Array, Array)
#17 /var/www/html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /var/www/html/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#19 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#20 /var/www/html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#21 /var/www/html/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('graphql-authent...', Array)
#22 /var/www/html/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('graphql-authent...', Array)
#23 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(201): craft\web\View->renderPageTemplate('graphql-authent...', Array, 'cp')
#24 /var/www/html/vendor/craftcms/cms/src/controllers/TemplatesController.php(102): craft\web\Controller->renderTemplate('graphql-authent...', Array)
#25 [internal function]: craft\controllers\TemplatesController->actionRender('graphql-authent...', Array)
#26 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#27 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#28 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('render', Array)
#29 /var/www/html/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction('templates/rende...', Array)
#30 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#31 /var/www/html/vendor/craftcms/cms/src/web/Application.php(278): yii\web\Application->handleRequest(Object(craft\web\Request))
#32 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#33 /var/www/html/web/index.php(28): yii\base\Application->run()
#34 {main}
```

**Comment by jamesedmonston** [comment]
@Tam did this happen after updating Craft? Did subsequent Craft updates resolve the issue?

**Comment by Tam** [comment]
@jamesedmonston Turns out it has something to do with `Craft::$app->getUser()` not having a user when the plugin goes to check if the current user is admin. Not sure why or how to fix it.

**Comment by Tam** [comment]
@jamesedmonston Found a fix:

```php
Craft::$app->on(Application::EVENT_INIT, function () {
    // ... check for admin, add CP urls ...
});
```
